on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Upload Release Asset

jobs:
  build-win:
    name: Build Windows Assets
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Build App
        run: |
          yarn --frozen-lockfile
          yarn build:win64
          yarn build-update
          yarn setup-release:win
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-assets
          path: |
            ./build/win/Genshin-Wish-Export-win.zip
            ./build/win/Genshin-Wish-Export-Setup.exe
            ./build/win/manifest.json
            ./build/win/?????.zip
  build-linux:
    name: Build Linux Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install libarchive-tools
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libarchive-tools
      - name: Build App
        run: |
          yarn --frozen-lockfile
          yarn build:linux
          yarn setup-release:linux
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-assets
          path: |
            ./build/linux/Genshin-Wish-Export-linux.tar.gz
            ./build/linux/Genshin-Wish-Export.pacman
            ./build/linux/Genshin-Wish-Export.deb
  create-release:
    name: Create release
    needs: [build-win, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Assets
        uses: actions/download-artifact@v4
        with:
          name: windows-assets
          path: ./release-assets
      - name: Download Linux Assets
        uses: actions/download-artifact@v4
        with:
          name: linux-assets
          path: ./release-assets
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          prerelease: false
          make_latest: true
          preserve_order: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./release-assets/Genshin-Wish-Export-win.zip
            ./release-assets/Genshin-Wish-Export-Setup.exe
            ./release-assets/Genshin-Wish-Export-linux.tar.gz
            ./release-assets/Genshin-Wish-Export.pacman
            ./release-assets/Genshin-Wish-Export.deb
            ./release-assets/manifest.json
            ./release-assets/?????.zip