on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Upload Release Asset

jobs:
  build-win:
    name: Build Windows Assets
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build App
        run: |
          yarn --frozen-lockfile
          yarn build:win64
          yarn build-update:win
          yarn setup-release:win
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-assets
          path: ./build/win/
  build-linux:
    name: Build Linux Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build App
        run: |
          yarn --frozen-lockfile
          yarn build:linux
          yarn setup-release:linux
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-assets
          path: ./build/linux/
  create-release:
    name: Create release
    needs: [build-win, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Assets
        uses: actions/download-artifact@v4
        with:
          name: windows-assets
          path: ./release-assets
      - name: Download Linux Assets
        uses: actions/download-artifact@v4
        with:
          name: linux-assets
          path: ./release-assets
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          make_latest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./release-assets/*